### PR TITLE
Removed unused assets.

### PR DESCRIPTION
**Pull request by bhamodi**
@tonyrzhang @pamoptly @mikeng13 - removed unused assets that were added in commit: https://github.com/optimizely/ios-demo/commit/f734694c008d91e18e023a7ce9664dfaae34f7a5

I tested by building the app locally.

### CODE REVIEW

**Comment by tonyrzhang** [comment]
@bhamodi were they not referenced in the proj?

**Comment by bhamodi** [comment]
The assets still exist @tonyrzhang but in the correct directory. The commit that added these files added them in 3 different directories but it was only needed in the `gilt/KitchenSink/KitchenSink/` directory.

**Comment by tonyrzhang** [comment]
@bhamodi gotcha. Cool thx! lgtm

**Comment by bhamodi** [comment]
:+1: Merging!

**Pull request merged**
